Script out inserts
squire40/LuresGalore pull request #5
Opened 2019-03-17 16:53 UTC by kation1

2019-04-22 19:40 UTC, killyosaur submitted a review, later dismissed

2019-04-29 19:09 UTC, squire40 requested changes
You need to re-order your inserts.  If you try to run these, you get constraint errors.

2019-04-30 04:37 UTC, kation1 commented
Constraint errors were from the autoincrement values staying after the rollback. 

Updated ROLLBACK to Commit

Added USE LuresGalore at beginning

2019-05-02 01:57 UTC, squire40 approved these changes

2019-05-02 01:57 UTC, merged